title: "My AI Blog"
description: "Deep Learning, AI, and Math"
url: "https://littlecottage.github.io"
baseurl: "/my-blog"  # Change if deploying to a different repo

repository: LittleCottage/my-blog

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      math: true
      read_time: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

collections:
  pages:
    output: true
    permalink: /:path/

exclude: [Gemfile, Gemfile.lock, node_modules, vendor]

